name: example
description: An example project

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.2
  test: ^1.16.5

flutter:
  uses-material-design: true