name: faster_driver
description: Script(s) to improve Integration Tests. Allows merging all the Integration tests into one file to run all tests at once
version: 0.0.3+1
homepage: https://github.com/tomaszpolanski/faster_driver

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  fasterdriver: main

dependencies:
  path: ^1.8.0
  args: ^2.0.0
  cli_util: ^0.3.0

dev_dependencies:
  test: ^1.16.8
