name: faster_driver
description: A set of tool to improve Flutter Driver
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0"

executables:
  fasterdriver: main

dependencies:
  path: ^1.8.0
  args: ^2.0.0
  cli_util: ^0.3.0

dev_dependencies:
  test: ^1.16.8

