name: faster_driver
description: A set of tool to improve Flutter Driver
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  args: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
