name: Build

on: [push, pull_request]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["tool"]
        version: ["stable"]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: pub get

      - name: Analyze
        working-directory: ${{ matrix.package }}
        run: dart analyze

      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: flutter test
